### ISSUE TITLE
Implement Docker build and push functions

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#1]
## User Story

Developers build their own applications and store them in the repository. The repository is prepared in advance.

## Acceptance Criteria

* Simple implementation of the artifact plugin mechanism through the Go language interface.
* Plugins for Docker builds to be implemented.
* NOT require jobs and plugins to run on Docker.
* NOT require separation of CLI, job, and plugin source code.

## Design & Specification

The `dacrane.yaml` file should read as follows

```yaml
kind: artifact
name: api
provider: docker
parameters:
  image: sample-api
  tag: latest
  dockerfile: ./Dockerfile
  repository:
    url: url
    user: user
    password: password
```

The `build` command builds a container image with local docker.

```bash
$ dacrane build [artifact]
```

The “publish" command publishes a container image to the specific registry. Container images must be built.

```bash
$ dacrane publish [artifact]
```

The “list” command displays a list of container image versions.

```bash
$ dacrane search versions [artifact]
```

The “unpublish” command removes the specific container image version from the local and remote registry.

```bash
$ dacrane unpublish [artifact]
```
