### ISSUE TITLE
Generate Dockerfile automatically

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#14]
## User Story

Developers want to build container images without having to write a Dockerfile for the standard build method. For example, after executing a build such as `go build` or `npm ci`, you need to run `./executable` and `npm start`.

 ## Acceptance Criteria

The following will cause npm to build JavaScript on docker.

```yaml
import: https://github.com/.../.../docker-npm.yaml
name: api
modules:
- name: api
  module: docker-npm
```

Together with #18, the following modules should be defined. This issue implements a `file` resource provider since there are not enough `file` resources.

```yaml
name: docker-npm
argument:
- name: version
  default: 16.20.1
- name: src_files
  default: "**/*.js"
- name: package
  default: ./package.json
- name: package-lock
  default: ./package-lock.json
- name: build
  default: npm ci
- name: run
  default: npm start
modules:
- name: dockerfile
  provider: resource/file
  parameters:
    filename: ./Dockerfile
    contents: >
      FROM node:${{ arg.version }}-alpine3.18
  
      COPY ${{ arg.src_files }} ${{ arg.src_files }}
      COPY ${{ }} ${{ }}
      COPY ./package-lock.json ./package-lock.json
  
      RUN npm ci
  
      CMD [ "npm", "start" ]
  - name: docker_build
    provider: artifact/docker
    parameters:
      name: ...
      image: ...
      tag: ...
      port: ...
      env:  ...
  ```
