### ISSUE TITLE
Dacrane Custom Plugin

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#29]
## User Story

Developers are willing to release their own plugins. In developing the plug-ins, there are some dependencies regarding middleware, and we would like to release them in containers.

## Acceptance Criteria

```yaml
modules:
- name: foo
  module: [docker_image_name]:[tag]/[data|resource]/[data_or_resource_name]
```
