### ISSUE TITLE
Resolve dependencies and implement batch deploy functionality

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#3]
## User Story

Users want to deploy from infrastructure to application with one command.

## Acceptance Criteria

* To be implemented according to the following design.
* To be able to deploy containers to the App Service using this function.

## Design & Specification

The following command creates all resources defined in `dacrane.yaml`. However, updating is not supported at this time.

```bash
$ dacrane up
```

The following command deletes all resources that had been created.

```bash
$ dacrane down
```

Wait for resources given in "dependencies".
For example, `foo` waits for the creation or update of `bar` when defined as follows

```yaml
kind: resource
type: providerA
name: foo
dependencies: [resource.bar]
parameters:
  a: 1
  b: 2

---

kind: resource
type: providerB
name: bar 
parameters:
  a: 1
  b: 2
```
