### ISSUE TITLE
Fix broken App Service sample code

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#54]
## User Story

I would like a fully working sample code.

## Acceptance Criteria

* Modify the code as follows to allow the image to be passed.

https://github.com/SIOS-Technology-Inc/dacrane/blob/main/example/app-services/dacrane.yaml#L31-L36

```yaml
parameter:
  type: object
  required: ["image", "tag"]
  properties:
    image: 
      type: object
      properties:
        image: { type: string }
        tag: { type: string }
```

```sh
$ dacrane apply local-dokcer local -a '{ image: ${{ instances.api-v1.modules.api-local-image }} }'
```

* Fix `docker-local` calls from `quick-start` as well.
* Add a note to README.md on how to deploy to local-docker.

It will take time to fix #52, so fix it to work in a workaround first.
