### ISSUE TITLE
Parameter reference function

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#7]
## User Story

Developers want to use artifact and resource parameters for defining artifacts and resources that depend on them. For example, they want to store container images by obtaining the credentials of the container repository.

## Acceptance Criteria

* The parameters of other resources should be able to be referenced. 
  * The format is `${ [kind]. [name]. [parameter_name] }`.
  * It should be possible to obtain the derived value after resource creation.
  * Referenced resources must be created or modified first. (related to #3 )
* Environment variables should be prefixed with `env` to avoid conflicts with the above. 
  * The format is`${ env.[ENVNAME] }`.

For example, `as` refers to the `name` of `asp` when defined as follows.
`asp` is created and modified before `as`.

```yaml
kind: resource
name: asp
provider: azure-app-service-plan
parameters:
  name: sample-asp
  resource_group_name: sample-rg
  location: "Japan East"

---

kind: resource
name: as
provider: azure-app-service
parameters:
  name: sample-as
  resource_group_name: sample-rg
  location: "Japan East"
  app_service_plan_id: ${ resource.asp.name } # read resource parameters
```
