### ISSUE TITLE
Multiple types of configuration functions

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#8]
## User Story

Developers want to run their applications in the cloud or on local PCs. Multiple configurations are represented as code, and the developer wants to easily switch between which configuration is used.

## Acceptance Criteria

The if property switches the resource to be created. (Use the functionality implemented in #7 .)

```yaml
if: ${{ data.config.service == "docker" }}
kind: resource
provider: docker
parameters: ...
---

if: ${{ data.config.service == "aks" }}
kind: resource
provider: azure-kubernetes-service
parameters: ...
```

Implement a `docker` resource provider.
The parameters are given as follows.

```yaml
kind: resource
name: docker
provider: docker
parameters:
  image: sample-api
  tag: ${{ data.argument.tag }}
  port: 3000:3000
  env:
    - name: PORT
      value: 3000
```

Ability to switch between local Docker and Azure App Services services.
