### ISSUE TITLE
Secret sharing function

### ISSUE THREAD

**Issue by t-ikeda-sti** [SIOS-Technology-Inc/dacrane#9]
## User Story

Developers want to minimize the definition of cloud credentials. However, they do not always use the same credentials; they may be dynamically generated or use different credentials.

## Acceptance Criteria

(Implemented also by #7 at the same time.)

**Comment by t-ikeda-sti** [comment]
Implemented also by #7 at the same time.

`data` kind allows passing authentication information, and references by expression allow dynamic authentication information to be passed.

The following is an example definition of `data` kind.

```yaml
kind: data
name: azure_credential
provider: environment
parameters:
  - name: subscription_id
  - name: tenant_id
  - name: client_id
  - name: username
  - name: password
    secret: true
```

The following is an example of `data` kind reference.

```yaml
parameters:
  credentials: ${{ data.azure_credential }}
  other_parameters: ...
```

The following is an example of a reference to a secret generated from a dependent resource.

```yaml
parameters:
  app_settings:
    DOCKER_REGISTRY_SERVER_URL: ${{ resource.acr.url }}
    DOCKER_REGISTRY_SERVER_USERNAME: ${{ resource.acr.user }}
    DOCKER_REGISTRY_SERVER_PASSWORD: ${{ resource.acr.password }}
  other_parameters: ...
```
